### ISSUE TITLE
Servicebinding status shows 'READY true' after referenced secret was deleted

### ISSUE THREAD

**Issue by ChunyiLyu** [servicebinding/runtime#350]
Given an example like:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workload
  name: workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload
  template:
    metadata:
      labels:
        app: workload
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        resources: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: binding-secret
type: Opaque
stringData:
  target: "service binding"
---
apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: controlled-resource
spec:
  service:
    apiVersion: v1
    kind: Secret
    name: binding-secret
  workload:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        app: workload
  env:
  - name: TARGET
    key: target
```

After the binding secret was deleted, service binding status still shows `READY true`

```
[~] $ k get servicebindings.servicebinding.io 
NAME                  SECRET                                 READY   REASON         AGE
controlled-resource   binding-secret                         True    ServiceBound   5s
[~] $ k delete secret/binding-secret
secret "binding-secret" deleted
...
[~] $ k get servicebindings.servicebinding.io 
NAME                  SECRET                                 READY   REASON         AGE
controlled-resource   binding-secret                         True    ServiceBound   3m8s
...
[~] $ k get servicebindings.servicebinding.io 
NAME                  SECRET                                 READY   REASON         AGE
controlled-resource   binding-secret                         True    ServiceBound   9m20s
```
